# Generated by Django 3.1.2 on 2020-11-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pet', '0002_auto_20201101_0512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'verbose_name': 'Департамент ЖКХ', 'verbose_name_plural': 'Департаменты ЖКХ'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Информация о вакцине', 'verbose_name_plural': 'Информации о вакцинах'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='petmodel',
            options={'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AlterModelOptions(
            name='prefecture',
            options={'verbose_name': 'Префектура', 'verbose_name_plural': 'Префектуры'},
        ),
        migrations.AlterModelOptions(
            name='shelter',
            options={'verbose_name': 'Приют', 'verbose_name_plural': 'Приюты'},
        ),
        migrations.AlterModelOptions(
            name='typevaccine',
            options={'verbose_name': 'Вакцина', 'verbose_name_plural': 'Вакцины'},
        ),
        migrations.AddField(
            model_name='petmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_photo'),
        ),
    ]
